[2024-10-06T03:07:46.403+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T03:07:46.449+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_dag.transform__1 manual__2024-10-06T03:07:32.353733+00:00 [queued]>
[2024-10-06T03:07:46.467+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_dag.transform__1 manual__2024-10-06T03:07:32.353733+00:00 [queued]>
[2024-10-06T03:07:46.468+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T03:07:46.504+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): transform__1> on 2024-10-06 03:07:32.353733+00:00
[2024-10-06T03:07:46.523+0000] {standard_task_runner.py:72} INFO - Started process 562 to run task
[2024-10-06T03:07:46.543+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_data_dag', 'transform__1', 'manual__2024-10-06T03:07:32.353733+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_dag.py', '--cfg-path', '/tmp/tmpg5kj3v6_']
[2024-10-06T03:07:46.557+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask transform__1
[2024-10-06T03:07:46.741+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_data_dag.transform__1 manual__2024-10-06T03:07:32.353733+00:00 [running]> on host 2a293f7fa826
[2024-10-06T03:07:46.981+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_data_dag' AIRFLOW_CTX_TASK_ID='transform__1' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T03:07:32.353733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T03:07:32.353733+00:00'
[2024-10-06T03:07:46.987+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T03:07:46.996+0000] {logging_mixin.py:190} INFO - Start transforming
[2024-10-06T03:07:47.008+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/stock_data_dag.py", line 90, in transform
    df = df.reset_index()[['date', 'code', 'high', 'low', 'open', 'close', 'adjust', 'volume_match', 'value_match']]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['date', 'code', 'high', 'low', 'open', 'close', 'adjust',\n       'volume_match', 'value_match'],\n      dtype='object')] are in the [columns]"
[2024-10-06T03:07:47.067+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_dag, task_id=transform__1, run_id=manual__2024-10-06T03:07:32.353733+00:00, execution_date=20241006T030732, start_date=20241006T030746, end_date=20241006T030747
[2024-10-06T03:07:47.134+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T03:07:47.139+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 75 for task transform__1 ("None of [Index(['date', 'code', 'high', 'low', 'open', 'close', 'adjust',\n       'volume_match', 'value_match'],\n      dtype='object')] are in the [columns]"; 562)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/stock_data_dag.py", line 90, in transform
    df = df.reset_index()[['date', 'code', 'high', 'low', 'open', 'close', 'adjust', 'volume_match', 'value_match']]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['date', 'code', 'high', 'low', 'open', 'close', 'adjust',\n       'volume_match', 'value_match'],\n      dtype='object')] are in the [columns]"
[2024-10-06T03:07:47.216+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-06T03:07:47.254+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T03:07:47.256+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
